### ISSUE TITLE
Fallback on invalid tags?

### ISSUE THREAD

**Issue by lahwaacz** [earwig/mwparserfromhell#102]
mwparserfromhell fails to parse [this page](https://wiki.archlinux.org/index.php/Emacs) properly, my suspicion is that's because of the un-escaped tag-like syntax used for various keybindings, e.g. `<TAB>`, `<RET>`, `<backspace>`, `<f1>`, `<f2>` etc.
MediaWiki has some elaborate fallbacks for invalid tags so the page is rendered correctly; does mwparserfromhell try to do the same?

**Comment by earwig** [comment]
I'm going to go out on a limb here and say this will be resolved by #42. Keeping this open so we can verify when that's resolved.

**Comment by timwu** [comment]
This issue appears to also affect the [.us](https://en.wikipedia.org/wiki/.us) page from wikipedia as well. After some number of `<locality>.<state>` blobs in the text, parsing appears to skip over wikilinks, identifying them as text. 

For my application, it wouldn't be too bad to just skip pages where this parse issue occurs. Not quite sure what the best approach to identifying that case though.

**Comment by earwig** [comment]
Unfortunately the usual solution of `skip_style_tags=True` to `mwparserfromhell.parse()` doesn't work there because they're not style tags.

I don't have a simple solution in mind right now. You _could_ muck around in the parser internals to make `skip_style_tags` skip _all_ tags, if that works for you, but it'll be a bit annoying.

**Comment by earwig** [comment]
To add, this isn't as simple as hard-coding a large list of valid tags like in [definitions.py](https://github.com/earwig/mwparserfromhell/blob/develop/mwparserfromhell/definitions.py) since they are extension-dependent. It would need to be a configuration option.

**Comment by Larivact** [comment]
Can somebody provide a minimal working example?
