### ISSUE TITLE
Legal title characters are not checked when parsing wikilinks

### ISSUE THREAD

**Issue by lahwaacz** [earwig/mwparserfromhell#104]
The [$wgLegalTitleChars](http://www.mediawiki.org/wiki/Manual:$wgLegalTitleChars) forbids the `<` and `>` characters by default, but mwparserfromhell allows them. Is this a bug or yet another example of site-specific configuration you don't like to see in the parser?

**Comment by earwig** [comment]
As it stands, the only characters we explicitly _prevent_ in wikilink titles are `[]{}|` and `\n`, for hopefully obvious reasons. I hadn't considered `<>`, though.

Based on that manual page, my reading of [`Parser::replaceInternalLinks2()`](https://github.com/wikimedia/mediawiki/blob/0e1c80e6e178be646e8deb3fa64fac7e7219938b/includes/parser/Parser.php#L2010), and some testing, `<>` are the only other "problem" characters that we should disallow. That is, these are characters that could never reasonably be enabled in titles, while others would boil down to site-specific config. So I'll add this.
