### ISSUE TITLE
UnicodeEncodeError in string_mixin.py

### ISSUE THREAD

**Issue by ysangkok** [earwig/mwparserfromhell#108]
On parsing the English Wikipedia page "Eastern Bloc", revision (oldid) 669389172.

```
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    print(parsed)
  File "/home/janus/.local/lib/python2.7/site-packages/mwparserfromhell/string_mixin.py", line 61, in __str__
    return bytes(self.__unicode__())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 1095: ordinal not in range(128)
<type 'exceptions.UnicodeEncodeError'>
```

**Comment by ricordisamoa** [comment]
Seems like the same problem as #107, i.e. py2's fault, not mwparserfromhell's.

**Comment by earwig** [comment]
Yeah, looks to be the same. Just avoid printing the parsed contents directly – do `print(unicode(parsed))` and it should be fine.

Since this is coming up, I might add a note to the documentation.
