### ISSUE TITLE
bugs in handling trailing spaces in numbered params

### ISSUE THREAD

**Issue by benwing** [earwig/mwparserfromhell#109]
This is using on branch 'develop' as of early July 16. Trailing spaces in numbered params are not stripped by MediaWiki; therefore, `preserve_spacing` should not operate, but it does.

    >>> x = mp.parser.Parser().parse("{{foo|bar |sc=Cyrl}}", skip_style_tags=True)
    >>> x
    u'{{foo|bar |sc=Cyrl}}'
    >>> x.filter_templates()[0].get("1")
    u'bar '
    >>> x.filter_templates()[0].add("1", "bar")
    u'bar '
    >>> x
    u'{{foo|bar |sc=Cyrl}}'
    >>> x.filter_templates()[0].get("1")
    u'bar '

Even worse, `remove()` appears to sometimes not simply remove the field, but leaves the spaces, and there's no `preserve_spacing` option:

    >>> x = mp.parser.Parser().parse("{{foo|bar |sc=Cyrl}}", skip_style_tags=True)
    >>> x
    u'{{foo|bar |sc=Cyrl}}'
    >>> x.filter_templates()[0].add("2", "bar")
    u'bar'
    >>> x
    u'{{foo|bar |sc=Cyrl|bar}}'
    >>> x.filter_templates()[0].add("1", "bar")
    u'bar '
    >>> x
    u'{{foo|bar |sc=Cyrl|bar}}'
    >>> x.filter_templates()[0].remove("1")
    >>> x
    u'{{foo| |sc=Cyrl|bar}}'
    >>> x.filter_templates()[0].add("1", "bar")
    u' bar'
    >>> x
    u'{{foo| bar|sc=Cyrl|bar}}'

Note how the space was left after removing the field, and then got inserted *before* the newly added param.

**Comment by earwig** [comment]
That is... odd. I will have a look.

**Comment by earwig** [comment]
> Trailing spaces in numbered params are not stripped by MediaWiki

[I didn't realize this](https://en.wikipedia.org/wiki/User:The_Earwig/Sandbox#template_whitespace_stripping), thanks for telling me! Why is this even true? Fixed in 4c25400. This solves the first issue. Still looking at the second one.

**Comment by earwig** [comment]
Okay – in the second case, my logic was completely wrong. I was treating a blank parameter the same way as an unspecified parameter. Fixed in 699d063.

**Comment by benwing** [comment]
Thanks for fixing this!
