### ISSUE TITLE
Parsing of behavior switches

### ISSUE THREAD

**Issue by lahwaacz** [earwig/mwparserfromhell#110]
The [behavior switches](https://www.mediawiki.org/wiki/Help:Magic_words#Behavior_switches) are currently parsed as plain text. It would be nice to parse them as a special node.

**Comment by earwig** [comment]
You're right, this is a missing node type. I'm not sure if we should have a whitelist of valid switches or just accept anything of the form `__ALLCAPS__` – I know extensions can define their own but I worry that there might be false positives. Will have to look into that.

Either way, this is included as part of issue #10 for v0.5.

**Comment by lahwaacz** [comment]
Didn't notice the old issue, sorry for the duplicate.

Anyway, in the client code it is easier to filter out false positives than to parse the switches manually. Also client code usually targets just one (or a couple of) specific wiki(s), so the list of valid switches can be handled there. If that's emphasized in the docs, I see no problem with that.
