### ISSUE TITLE
Templates with empty name

### ISSUE THREAD

**Issue by lahwaacz** [earwig/mwparserfromhell#111]
On [this page](https://wiki.archlinux.org/index.php?title=Font_Configuration_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)&oldid=382922#.E9.AB.98.E7.BA.A7LCD.E8.BF.87.E6.BB.A4.E5.99.A8.E8.AF.B4.E6.98.8E) there has been a typo:

    {{|icLCD过滤器}}

MediaWiki renders this as plain text, but mwparserfromhell parsed it as a template with empty string as the template name.

**Comment by earwig** [comment]
Fixed in f16c7e2.
