### ISSUE TITLE
Template not found?

### ISSUE THREAD

**Issue by symac** [earwig/mwparserfromhell#119]
Trying to parse pages from English wikipedia, I sometime find that some templates are not found. For example, the following script won't extract the Infobox person template which is present. Is this a known issue or am I missing something?

```python
# -*- coding: utf-8 -*-
#!/usr/bin/python
import mwparserfromhell
import pywikibot as wikipedia

site = wikipedia.Site("en", 'wikipedia')
page = wikipedia.Page(site, u"Alvin Toffler")

parsedText = mwparserfromhell.parse(page.text)
templates = parsedText.filter_templates()

for tpl in templates:
	print tpl.name
```

**Comment by earwig** [comment]
Looks like a symptom of #40. The temporary fix is this:

```python
parsedText = mwparserfromhell.parse(page.text, skip_style_tags=True)
```

**Comment by symac** [comment]
Thanks @earwig sorry I hadn't found the existing bug. It fixes things yes.
