### ISSUE TITLE
Table parsing fails if unclosed tag finds a match in a different row

### ISSUE THREAD

**Issue by clokep** [earwig/mwparserfromhell#122]
Using mwparserfromhell 0.4.2 I've had some issue with unclosed tags 'eating' other rows. If you have some wiktext with a tag (e.g. ``''Italic''``) in two different rows, but in the first instance you forget to close it, mwparserfromhell combines the rows together into a single tag.

Some (annotated) wikitext that shows this:
```
{| class="wikitable"
|-
! Header text !! Header text
|-
| Example 1-1 || ''Example 1-2 <-- Unclosed tag!!!
|-
| Example 2-1 || ''Example 2-2'' <-- Same type of tag on another row!!!
|}
```

This gets parsed into only 2 rows, instead of the expected 3

A runnable test case to illustrate the issue:
```python
import mwparserfromhell

import unittest


# Break the table into a set of rows for content.
def filter_tr(node):
    return isinstance(node, mwparserfromhell.nodes.tag.Tag) and node.tag == 'tr'


class TestTableHangingTags(unittest.TestCase):
    def test_valid(self):
        TEXT = """{| class="wikitable"
|-
! Header text !! Header text
|-
| Example 1-1 || Example 1-2
|-
| Example 2-1 || Example 2-2
|}
"""

        wikicode = mwparserfromhell.parse(TEXT)
        table = wikicode.get(0)
        rows = table.contents.filter(recursive=False, matches=filter_tr)

        self.assertEqual(len(rows), 3)  # passes

    def test_hanging_tag(self):
        TEXT = """{| class="wikitable"
|-
! Header text !! Header text
|-
| Example 1-1 || ''Example 1-2
|-
| Example 2-1 || ''Example 2-2''
|}
"""

        wikicode = mwparserfromhell.parse(TEXT)
        table = wikicode.get(0)
        rows = table.contents.filter(recursive=False, matches=filter_tr)

        self.assertEqual(len(rows), 3)  # fails


if __name__ == '__main__':
    unittest.main()
```

I think I've also seen a similar issue with an unclosed `<small>` tag, but I was unable to reproduce that in a smaller test case. Please let me know if there's anything I can do to help!

**Comment by earwig** [comment]
Yep... this is a very common issue, identified as #40. The temporary fix is to pass `skip_style_tags=True` to `mwparserfromhell.parse()` to disable `''` and `'''` entirely. This wouldn't fix the issue with `<small>`, though.

Unless someone comes up with a revolutionary way of storing overlapping nodes in the same tree structure, the eventual fix will be explicitly telling mwparserfromhell what you're interested in parsing (templates/links/wikicode tables vs. embedded HTML, etc) and it will ignore the other types of nodes.

**Comment by clokep** [comment]
Oops, sorry for filing the duplicate! Thanks for the trick with `skip_style_tags`, that fixed my issue.

My fix for the `<small>` issue is to use a :hammer: on it: `text = re.sub(r'</?small>', '', text)`
