### ISSUE TITLE
Block recognized as text but should be template

### ISSUE THREAD

**Issue by tbicr** [earwig/mwparserfromhell#127]
for next wikipedia pages content `Infobox country` recognized as text but expected template:

- https://en.wikipedia.org/wiki/El_Salvador
- https://en.wikipedia.org/wiki/Ghana 
- https://en.wikipedia.org/wiki/Norway

**Comment by earwig** [comment]
Can't reproduce:

```python
>>> code = mwparserfromhell.parse(ghana)
>>> t = code.filter_templates()[6]
>>> t.name
u'Infobox country\n'
>>> type(t)
<class 'mwparserfromhell.nodes.template.Template'>
>>> t[:500]
u'{{Infobox country\n|conventional_long_name = Republic of Ghana\n|common_name = Ghana\n|image_flag = Flag of Ghana.svg\n|image_coat =Coat of arms of Ghana.svg\n|image_map = Ghana (orthographic projection).svg\n|map_caption = {{map caption |countryprefix= |location_color=dark green |region= |region_color= |subregion= |subregion_color= }}\n|national_motto="Freedom and Justice"\n|national_anthem = {{vunblist |\'\'[[God Bless Our Homeland Ghana]]<ref>{{cite web |url=http://www.emefa.myserver.org/Ghana.mp3 |tit'
```

Are you on an old version of mwparserfromhell?

**Comment by tbicr** [comment]
pypi mwparserfromhell==0.4.2, python 3.4
Python 3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2] on linux

**Comment by tbicr** [comment]
0 <class 'mwparserfromhell.nodes.template.Template'> {{about|the modern country of Ghana|the Ghana Empire ([[Circa|c.]] 790–1076) northwest of modern Ghana|Ghana Empire|other uses|}}
    1 <class 'mwparserfromhell.nodes.text.Text'> 
    2 <class 'mwparserfromhell.nodes.template.Template'> {{Multiple issues|
    {{disputed|date=May 2015}}
    {{refimprove|date=May 2015}}
    }}
    3 <class 'mwparserfromhell.nodes.text.Text'> 
    4 <class 'mwparserfromhell.nodes.template.Template'> {{EngvarB|date=August 2014}}
    5 <class 'mwparserfromhell.nodes.text.Text'> 
    6 <class 'mwparserfromhell.nodes.template.Template'> {{Use dmy dates|date=May 2015}}
    7 <class 'mwparserfromhell.nodes.text.Text'> {{Infobox country
    |conventional_long_name = Republic of Ghana
    |common_name = Ghana
    |image_flag = Flag of Ghana.svg
    |image_coat =Coat of arms of Ghana.svg
    |image_map = Ghana (orthographic projection).svg
    |map_caption =
    8 <class 'mwparserfromhell.nodes.template.Template'> {{map caption |countryprefix= |location_color=dark green |region= |region_color= |subregion= |subregion_color= }}
    9 <class 'mwparserfromhell.nodes.text.Text'> |national_motto="Freedom and Justice"
    |national_anthem =

**Comment by tbicr** [comment]
The same behaviour on github version for python 2.7 and 3.4

**Comment by lahwaacz** [comment]
I'm seeing the same behaviour as @tbicr...

**Comment by earwig** [comment]
My mistake. Couldn't reproduce originally because I wasn't giving mwpfh the whole page. This smells like #40.

**Comment by earwig** [comment]
Since `skip_style_tags` bypasses the error, I'm going to assume this is #40, even though I don't see the problem within the template code (it's fairly complex so I'm probably just missing it).

So: the workaround is to pass `skip_style_tags=True` to `mwparserfromhell.parse()`.
