### ISSUE TITLE
C tokenizer exited with non-empty token stack.

### ISSUE THREAD

**Issue by wnielson** [earwig/mwparserfromhell#132]
Got this error today:
```
mwparserfromhell.parser.ParserError: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.
```

The page causing this error has ID ```23306180```.

**Comment by earwig** [comment]
@wnielson Which page? The English Wikipedia page with that ID is [Regina Harris Baiocchi](https://en.wikipedia.org/wiki/Regina_Harris_Baiocchi), which mwparserfromhell handles fine.

**Comment by earwig** [comment]
Closing due to lack of details; I'm not sure how to approach this. Please reopen if you can provide some example input that causes this...
