### ISSUE TITLE
failing to identify some sections

### ISSUE THREAD

**Issue by kjschiroo** [earwig/mwparserfromhell#134]
The following script fails to identify several sections in the input.

    import mwparserfromhell as mwp
    input = open("bad_input.txt", "r").read()
    # There are 32 sections in bad_input.txt
    sections = mwp.parse(input).get_sections()
    print(len(sections))
    # 3

[bad_input.txt](https://github.com/earwig/mwparserfromhell/files/59822/bad_input.txt)
The input was retrieved from [this url](https://en.wikipedia.org/w/index.php?title=User_talk:Ian.thomson&action=edit&oldid=692048144).

It ends up finding 3 sections, the first section has several unidentified ones inside of it.

My version is `mwparserfromhell==0.4.3`

**Comment by lahwaacz** [comment]
Interestingly `filter_headings` produces the expected result (all 32 headings).

**Comment by kjschiroo** [comment]
Yeah, I noticed that. I wasn't sure if the two were supposed to have a one-to-one relationship or if there was something more complicated going on underneath.

**Comment by earwig** [comment]
Well, I'll take a look tonight.

**Comment by earwig** [comment]
Wellp... as expected, this is a symptom of #40, due to an unclosed bit of italics here:

    ''Also, please sign your posts in talk pages with four tildes (<nowiki>~~~~</nowiki>)

The current solution is to pass `skip_style_tags=True` to `mwparserfromhell.parse()`:

```python
>>> len(mwp.parse(t).get_sections())
3
>>> len(mwp.parse(t, skip_style_tags=True).get_sections())
33
```
