### ISSUE TITLE
Wikicode.get_sections on [[w:en:Animal testing]]

### ISSUE THREAD

**Issue by HazardSJ** [earwig/mwparserfromhell#135]
Please look at how mwparserfromhell treats `get_sections()` for the `Wikicode` of [[[Animal testing](https://en.wikipedia.org/wiki/Animal_testing)]]. It identifies only 3 sections (the lead section, "Definitions", and "Further reading"), so if anything in the page's source if affecting this, it might have started in the "Definitions" section and ended in the "Bibliography" section (except the "Bibliography" is so basic that I don't see how this could be).

I'm running the latest version from develop, and I've tested both with and without the C parser this time.

**Comment by earwig** [comment]
@HazardSJ can you take a look at the issue filed just before this one (#134) and see if it's the same thing?

**Comment by HazardSJ** [comment]
@earwig, it actually does seem to be the same. Even stranger is that both the page in #134 and the page I referred above both have 32 section headings, and both recognize 3 sections from `get_sections()` without `skip_style_tags=True` (P.S. wow, this workaround is familiar from ages ago, come to think of it).

**Comment by earwig** [comment]
I was actually in the middle of adding a caveat to the docs about this, but you reported the issue before I had a chance to finish writing it up.
