### ISSUE TITLE
Unclosed HTML tags cause strange section parsing

### ISSUE THREAD

**Issue by yuvipanda** [earwig/mwparserfromhell#138]
If you look at https://en.wikipedia.org/w/index.php?title=Wikipedia:Teahouse/Questions/Archive_95&oldid=558621423, under the section 'Signatures':

```
: How can I change that??? <span style="background: black"><span style="font-family:'Segoe Script'">&nbsp;
```

This span tag isn't really closed, and this is having weird effects in splitting sections in mwpfh.

With:

```python
from mwparserfromhell import parse

doc = parse(open('text.wm').read(), skip_style_tags=True)

for sec in doc.get_sections(include_lead=True, flat=True):
    print(sec.filter_headings())
```

I'm getting 
```
['== Creating an Ad ==', '== Signature ==']
```` 
with that unclosed span tag and the correct 

````
['== Creating an Ad ==']
['== Signature ==']
```

without it.

**Comment by earwig** [comment]
I think this the same as #40.

**Comment by yuvipanda** [comment]
yup, probably.
