### ISSUE TITLE
Question: extracting internal links from dump

### ISSUE THREAD

**Issue by gg4u** [earwig/mwparserfromhell#139]
Question: possible to use the tool to extract internal links from xml dump?
Does the tool handle redirect (transitive)?

**Comment by earwig** [comment]
Yes, it parses pages from dumps as well as any other type of page, but you'll need another program to read the dumps themselves.

I am not sure I understand your second question fully, but it does not handle redirects because redirects are encoded the same as regular links in wikitext.

**Comment by jfolz** [comment]
@gg4u mwparserfromhell is a parser for MediaWiki code. You cannot know whether a page is a redirect or what kind of thing it points to unless you ask the API of that MediaWiki instance.

**Comment by gg4u** [comment]
@jfolz @earwig thank you for clarification.

**Comment by ricordisamoa** [comment]
> Some links are like [[Gunther Stent|Stent, Gunther Siegmund]]
> The first is the canonical form, but what does the second token represent?
> e.g. I try:
> parse('Stent, Gunther Siegmund')
> 
> Traceback (most recent call last):
> 
> File "", line 1, in
> 
> File "", line 6, in parse
> 
> KeyError: 'revisions'
> 
> What does this error mean?

The page title is before `|`, the link label is after (https://www.mediawiki.org/wiki/Help:Links#Internal_links). Also you should not expect target pages to always exist, thus check for `"revisions"` in `res["query"]["pages"].values()[0]`.

**Comment by lahwaacz** [comment]
1. The arguments are documented for the `ifilter()` method, all `ifilter_*` and `filter_*` methods take the same arguments. http://mwparserfromhell.readthedocs.org/en/latest/api/mwparserfromhell.html?highlight=filter_templates#mwparserfromhell.wikicode.Wikicode.ifilter

2. See https://en.wikipedia.org/wiki/Help:Link#Piped_link
    The error means that you are most likely accessing a page that does not exist on the wiki. You should handle the API errors (part of `res["query"]` in your code) or use a client library that does this for you.

3. mwparserfromhell is a parser for wikitext, not XML dumps.

**Comment by gg4u** [comment]
@lahwaacz  XML dump come in wikitext, right?
can mwparser be used to manipulate content in between of <pages> or is it completely different syntax from wikitext?

**Comment by lahwaacz** [comment]
@gg4u XML dumps come in XML. You need to use an XML parser (such as [this one](https://pythonhosted.org/mediawiki-utilities/core/xml_dump.html#mw-xml-dump)) to parse the dump, extract the wikitext encoded therein and pass it to mwparser.

**Comment by suhassumukhv** [comment]
@earwig But given `wikitext` as `#REDIRECT [[Tom Hanks#Personal life]] {{Redirect category shell|1= {{R from son}} {{R to section}} }}` ([Chet Hanks](https://en.wikipedia.org/w/index.php?title=Chet_Hanks&redirect=no)), do you identify this as a Redirect syntax?

**Comment by earwig** [comment]
@suhassumukhv Currently no, but we will in the future (it's been an open issue for a while: #10)
