### ISSUE TITLE
get_sections() fails to parse certain sections.

### ISSUE THREAD

**Issue by eggpi** [earwig/mwparserfromhell#140]
I've observed the following behavior when trying to parse the page [Décadence](https://fr.wikipedia.org/wiki/D%C3%A9cadence) from the French Wikipedia:

~~~
import mwparserfromhell
mwparserfromhell.__version__
### '0.4.3'
with open('decadence') as f:
    wikitext = f.read()

sections = mwparserfromhell.parse(wikitext).get_sections(
    include_lead = True, include_headings = True, flat = True)
len(sections)
### 4
sections[0].get(0)
### u'{{Voir homonymes|D\xe9cadence (homonymie)}}'
sections[1].get(0)
### u'== D\xe9finition =='
sections[2].get(0)
### u'== Histoire =='
sections[3].get(0)
### u'==Contextualisation=='
~~~

I omitted the full contents of the sections for brevity, but the wikicode for sections Historique du thème, Concordances and Voir aussi have all been included under the Contextualisation section. My expectation was that they would each be parsed as separate sections.

For what it's worth, this is not the only page where I've seen this happen in the French Wikipedia, but I don't recall this happening in the English Wikipedia. Am I doing something wrong here?

**Comment by earwig** [comment]
Can you check if this is the same as #134?

**Comment by eggpi** [comment]
Yep, looks like it! Adding `skip_style_tags = True` gets me the correct sections, and so does fixing the unclosed `''` in the line `** 390 : ''massacre de [[Thessalonique]]` (which I just did in the article).

**Comment by earwig** [comment]
Thanks!

**Comment by jfolz** [comment]
@earwig maybe `skip_style_tags = True` should be the default ;)

**Comment by earwig** [comment]
It'll be removed in 0.5 or 1.0 when I create a proper config system for describing what kinds of things you are interested in parsing...

Until I get around to that, I'll avoid other changes to the API to avoid confusion.
