### ISSUE TITLE
Readme description on windows installation may cause error

### ISSUE THREAD

**Issue by qxx** [earwig/mwparserfromhell#141]
>  On Windows, make sure you have the latest version of pip installed by running `pip install --upgrade pip`.

`pip install --upgrade pip` may cause error on Windows due to Windows' limitation, as described in [this issue](https://github.com/pypa/pip/issues/1299).

The correct way to upgrade pip on Windows is `python -m pip install -U pip`

**Comment by earwig** [comment]
Hmm... I'll just take the line out; I don't need to give specific instructions on how to upgrade one's software.
