### ISSUE TITLE
It would be desirable to report parsing issues due to max depth reached

### ISSUE THREAD

**Issue by hgaleote** [earwig/mwparserfromhell#143]
Not really a bug, just a comment.

Since the tokenizer's maximum depth is stricter than that in the MediaWiki software, sometimes valid wikicode is wrongly parsed without emitting any warning notice. It would be good to have a status flag in order to be aware when that happens.

For example, if we parse 14 nested templates (valid code in MediaWiki), the outer one is given as text because MAX_DEPTH has been reached, but there is no communication to the user about this issue:

```python
txt = """{{a|
 {{b|
  {{c|
   {{d|
    {{e|
     {{f|
      {{g|
       {{h|
        {{i|
         {{j|
          {{k|
           {{l|
            {{m|
             {{n}}
            <!--m-->}}
           <!--l-->}}
          <!--k-->}}
         <!--j-->}}
        <!--i-->}}
       <!--h-->}}
      <!--g-->}}
     <!--f-->}}
    <!--e-->}}
   <!--d-->}}
  <!--c-->}}
 <!--b-->}}
<!--a-->}}"""

>>> tree = mwparserfromhell.parse(txt)
>>> [(type(x), str(x)[:10]) for x in tree.nodes]
[(mwparserfromhell.nodes.template.Template, '{{a|\n {{b|'),
 (mwparserfromhell.nodes.text.Text, '\n'),
 (mwparserfromhell.nodes.comment.Comment, '<!--a-->'),
 (mwparserfromhell.nodes.text.Text, '}}')]
```

**Comment by earwig** [comment]
This will be fixed at some point when I work on other related bugs. Thanks for reporting.
