### ISSUE TITLE
Could add methods Rename and Remove for template parameters

### ISSUE THREAD

**Issue by bl79** [earwig/mwparserfromhell#146]
Could you add in the parser support for remove many parameters by List, like:
```
def removeTplParameters(tpl, keysList):
	for k in keysList:
		tpl.remove(k)		
```

Also, add method for rename parameters, like:
```
def renameParam(tpl, name, newname):
	if tpl.has(name):
		tpl.add(newname, tpl.get(name).value, True, name)
		tpl.remove(name)
```

**Comment by earwig** [comment]
I don't really see the point of the first one. It's just a for loop.

The second one can be done a lot more easily with `tpl.get(name).name = newname`.
