### ISSUE TITLE
Emphasis spanning sections

### ISSUE THREAD

**Issue by nettrom** [earwig/mwparserfromhell#151]
Came across an issue when parsing https://en.wikipedia.org/w/index.php?title=User_talk:JoeHebda&oldid=718781560

There's an unclosed emphasis in a section that causes the nodes list to contain a single item that spans several sections up until the next emphasis. I've attached the smallest amount of wikitext that I could extract that exemplifies the behaviour. Here's example code that'll show the problem:

```python
import mwparserfromhell, codecs
with codecs.open('mwparserfromhell_testcase.txt', 'r', 'utf-8') as infile:
     wikitext = ''.join(infile)
ptext = mwparserfromhell.parse(wikitext)
```

Now, `ptext.nodes[6]` should contain a large block of text. The problem is technically found in `ptext.nodes[2]`, where the emphasis is not closed properly, causing mwparserfromhell to match the emphasis parts in (perhaps) unexpected ways.

[mwparserfromhell_testcase.txt](https://github.com/earwig/mwparserfromhell/files/251280/mwparserfromhell_testcase.txt)

**Comment by earwig** [comment]
See #40.

`skip_style_tags=True` as an argument to `mwparserfromhell.parse()` should resolve this temporarily.
