### ISSUE TITLE
HTML comments not ignored when parsing templates

### ISSUE THREAD

**Issue by Abbe98** [earwig/mwparserfromhell#154]
Example:
```
import mwparserfromhell
text = "{{Template<!-- comment -->|test = value}}"
wikicode = mwparserfromhell.parse(text)
print(wikicode.filter_templates()[0].name)
```
prints: `Template <!-- comment -->`

**Comment by earwig** [comment]
This is the correct behavior.

**Comment by earwig** [comment]
Oh, if you want to test for the name of a template, use [`matches`](http://mwparserfromhell.readthedocs.io/en/latest/api/mwparserfromhell.html#mwparserfromhell.wikicode.Wikicode.matches), which strips formatting and does some normalization:

    >>> name = wikicode.filter_templates()[0].name
    >>> name.matches("Template")
    True
    >>> name.matches("Something")
    False

**Comment by Abbe98** [comment]
Okey, Thanks!
