### ISSUE TITLE
Installation on the wiki Tool labs

### ISSUE THREAD

**Issue by bl79** [earwig/mwparserfromhell#156]
How to install the parser on Tool labs? There `pip install` does not work. Also `python setup.py install` (after `git clone ...`) give error "permission denied".

And the question is if possible install the parser. Maybe I'll use it in few projects in different directories. So  should put it in the directory upper the projects folders. But I don't understand how `import` a module from the upper folder, and how to change the `PYTHONPATH`.

**Comment by earwig** [comment]
Use a [virtual environment](http://docs.python-guide.org/en/latest/dev/virtualenvs/). mwparserfromhell is no different from other python software in this case.

**Comment by Riamse** [comment]
Try running those commands with `--user` . But otherwise I agree with @earwig .

**Comment by legoktm** [comment]
Also, I think its already installed on tool labs...?

**Comment by bl79** [comment]
I installed the "virtual environment", and via it the dev-version of parser from git (as writen in README). But then began the incompatibility problems with Python 2.7 of Tool labs. 
The example from the README file (start without pywikibot) breaks down with error that there is no package "urllib.parse" with "urlencode". This "urllib.parse" use Python 3, but at 2.7 the "urlencode" and "qoute" included in "urllib". Maybe after show up and other problems of 2.7, for example with utf-8 and `print ()`...
Is it possible there somehow update the version of Python?

**Comment by Riamse** [comment]
you can compile your own python and install it to ~/.local/

**Comment by earwig** [comment]
Python 3 is already installed on Tool Labs as `python3`.

**Comment by Riamse** [comment]
that too

**Comment by bl79** [comment]
Maybe I made a mistake that the problem is not in the parser, but in the example of README file that uses:
```
from urllib.parse import urlencode
from urllib.request import urlopen
```

I ran a simple script (only "text", parsing templates contained in it, and print it) with "python3. It works: `python3 test.py`

**Comment by Riamse** [comment]
great!

**Comment by vladiscripts** [comment]
Which version of mwparserfromhell is installed on "Tool labs"? 
Major v0.4.3 spoils a tables in pages by adding to them code '|' (#148). I'm afraid to use automatically this required parser in my bot.

**Comment by earwig** [comment]
I really just suggest using a virtual environment and `python setup.py install`ing the develop branch from within it. I don't control the tool labs install, so I'm not sure how out of date it can get.
