### ISSUE TITLE
Ask: How to remove a template from text?

### ISSUE THREAD

**Issue by vladiscripts** [earwig/mwparserfromhell#159]
Next example removes only name from template, but itself remains.

```
text = "{{tpl_name | {{sub template}} some text}}"
wikicode = mwparserfromhell.parse(text)
wikicode.remove('tpl_name')
# result:  {{ | {{sub template}} some text}}
```

**Comment by lahwaacz** [comment]
Use [wikicode.filter_templates](https://mwparserfromhell.readthedocs.io/en/latest/api/mwparserfromhell.html#mwparserfromhell.wikicode.Wikicode.filter_templates) to get the exact instance you want to remove:

```python
for template in wikicode.filter_templates():
    if template.name.matches("tpl_name"):
        wikicode.remove(template)
```

**Comment by vladiscripts** [comment]
Thank you!
