### ISSUE TITLE
handling of paragraph breaks

### ISSUE THREAD

**Issue by tobiasschweizer** [earwig/mwparserfromhell#163]
Is there a way to convert newlines to paragraphs using `mwparserfromhell`?

Whenever two newlines occur after one another, I would like to wrap the whole thing with `<p>`.

https://en.wikipedia.org/wiki/Wikipedia:Line-break_handling

**Comment by lahwaacz** [comment]
That's much more complicated than converting _every_ `\n\n` to `<p>`. Consider for example
```
* foo

* bar
```
Although there is a blank line, MediaWiki does not add any `<p>` because everything is inside `<li>`.

**Comment by tobiasschweizer** [comment]
I am dealing with source code that is converted to HTML by the MediaWiki-system and it generates the `<p>` correctly. 

However, I want to convert it to XML directly from source and so I think `mwparserfromhell` would have to do whatever a MediaWiki-system would do to handle the paragraphs (it already handles links, tables etc. in that way).

test.mw:
```
This is a test paragraph

and this is another
```

`pandoc -f mediawiki test.mw -o test.html`

test.html
```
<p>This is a test paragraph</p>
<p>and this is another</p>
```

I thought about converting the HTML to XML but the references are easier to process in mediawiki than in the HTML. Also, I just need a specific part of the file which is delimited by HTML comments in the wiki source.

**Comment by tobiasschweizer** [comment]
I found this when I looked for an XSLT transformation: <http://stackoverflow.com/questions/5501832/create-paragraphs-with-xsl>

I could just post-process my XML. However, it would be nicer if `mwparserfromhell` would do it directly.

**Comment by earwig** [comment]
I think this is out of the scope of what mwparserfromhell tries to do. We aren't really interested in representing wikicode as HTML to this extent, and adding that functionality would require a lot of extra logic. Another library like [Parsoid](https://www.mediawiki.org/wiki/Parsoid), that has an awareness of HTML, may be more appropriate here.
