### ISSUE TITLE
Parsing WikiCode to HTML

### ISSUE THREAD

**Issue by Srijancse** [earwig/mwparserfromhell#166]
Is there a way, I can use mwparserfromhell, to parse wikitocode to HTML?

**Comment by lahwaacz** [comment]
No. See #161.

**Comment by earwig** [comment]
[Parsoid](https://www.mediawiki.org/wiki/Parsoid) might be best here.

**Comment by Srijancse** [comment]
The thing is, parsoid is quite heavy and using it for offline editing, doesn't suits! Since, mwparserfromhell, is a powerful parser, will someone be working on the HTML parsing in future?

**Comment by earwig** [comment]
I don't think so. mwparserfromhell's output structure is designed to be easy to manipulate for bots or tools, especially those that need to re-serialize it as wikitext with minimal changes and no other dependencies.

Building HTML would require a lot of logic we don't have yet, like actually expanding templates onwiki somehow. I guess #100 exists, though.

**Comment by Srijancse** [comment]
> I don't think so. mwparserfromhell's output structure is designed to be easy to manipulate for bots or tools, especially those that need to re-serialize it as wikitext with minimal changes and no other dependencies.

I agree. Actually, I was building an offlineextension for wikieditor, and was looking for ways to use mwparserfromhell. But, I agree, that it seems to be tough to build HTML using it!
