### ISSUE TITLE
two italic paragraphs get collapsed

### ISSUE THREAD

**Issue by tobiasschweizer** [earwig/mwparserfromhell#167]
If two italic paragraphs follow after one another

```
''Test''

''test''
```

they get collapsed into this 

```
<i>Test''''test</i>
```

However, this should be
```
<i>Tes</i>

<i>test</i>
```

**Comment by tobiasschweizer** [comment]
using mwparserfromhell (0.4.3)

**Comment by lahwaacz** [comment]
Seems to work fine in master:

```python
>>> import mwparserfromhell
>>> mwparserfromhell.__version__
'0.5.dev0'
>>> w = mwparserfromhell.parse("""
... ''Test''
... 
... ''test''
... """)
>>> print(w.get_tree())
\n
<
      i
>
      Test
</
      i
>
\n\n
<
      i
>
      test
</
      i
>
\n
```

**Comment by tobiasschweizer** [comment]
I got the current version with pip2.7

Could you tell what the possible difference is between the versions?

**Comment by tobiasschweizer** [comment]
How could I test dev version without messing up my version installed with pip?

**Comment by lahwaacz** [comment]
The diff is [here](https://github.com/earwig/mwparserfromhell/compare/v0.4.3...develop). For installation from git, see the [Installation section](https://github.com/earwig/mwparserfromhell#installation) or [pip documentation](https://packaging.python.org/installing/#installing-from-vcs). Use a virtual environment if you need multiple versions.

**Comment by earwig** [comment]
I don't think I fixed any bugs relating to that between 0.4.3 and now. I tested in a virtualenv and both versions do the correct thing. So I suspect the behavior you're noticing is related to the surrounding context of the text.

**Comment by tobiasschweizer** [comment]
Could you please post the complete example you tried?

**Comment by tobiasschweizer** [comment]
Damn, it was my fault. Sorry! I did some kind of preprocessing that messed it up.

Sorry!
