### ISSUE TITLE
Provide wheels for Linux on pypi

### ISSUE THREAD

**Issue by legoktm** [earwig/mwparserfromhell#170]
It would be nice if wheels were available for Linux users on pypi so it didn't have to be built when installing.

**Comment by Riamse** [comment]
mwparser on wheels

**Comment by legoktm** [comment]
After reading [PEP 513](https://www.python.org/dev/peps/pep-0513/), this is more complicated than it appears at first. 

We should investigate setting up something like https://github.com/pypa/python-manylinux-demo so the wheels are built automatically.

**Comment by earwig** [comment]
We'll try this for 0.5.
