### ISSUE TITLE
External links incorrectly contain adjacent templates

### ISSUE THREAD

**Issue by Larivact** [earwig/mwparserfromhell#179]
```python
>> import mwparserfromhell as mw
>> tree = mw.parse('http://example.com{{dead link}}')
>> tree.filter_external_links()[0].url
http://example.com{{dead link}}

**Comment by earwig** [comment]
It depends on the contents of the template. For example, `http://example.com/foo{{!}}bar` is (correctly) parsed as a complete link. I'm not sure what can be done here.

**Comment by Larivact** [comment]
Huh, the templates really pose a problem for MediaWiki AST parsers. Maybe you could let the user configure certain templates as link-ending?

**Comment by Larivact** [comment]
Let the user configure which templates are allowed in links and make all other templates end links.

**Comment by Larivact** [comment]
The name really starts to make sense when you factor in templates.

**Comment by Larivact** [comment]
I guess I just have to also check the url for the `dead link` template.
I think this should be added to the caveats section of the readme.
