### ISSUE TITLE
Template not recognized under weird circumstance

### ISSUE THREAD

**Issue by Larivact** [earwig/mwparserfromhell#183]
>>> import mwparserfromhell as mw
    >>> mw.parse('<x><x><x><x><x><x><x><x><x><x><x><x><x><x>[[{{x}}').filter_templates()
    []

Ran into this weird issue while parsing an article. This is the most minimal example I could figure out.
Why 14 tags? I don't know. Remove one and the problem no longer occurs. Add a space between the square brackets and it no longer happens.

**Comment by Riamse** [comment]
Seems to be on the Tokeniser end of things:

```python
s = "<x><x><x><x><x><x><x><x><x><x><x><x><x><x>[[{{x}}"
>>> mwparserfromhell.parser.tokenizer.Tokenizer().tokenize(s)
[Text(text='<x><x><x><x><x><x><x><x><x><x><x><x><x><x>[[{{x}}')]
>>> mwp.parser.CTokenizer().tokenize(s)
[Text(text='<x><x><x><x><x><x><x><x><x><x><x><x><x><x>[[{{x}}')]
```
Similarly alarming is the time it takes to tokenise:
```python
>>> timeit.timeit(lambda: mwparserfromhell.parser.tokenizer.Tokenizer().tokenize(s), number=10)
15.516502680955455
>>> timeit.timeit(lambda: mwp.parser.CTokenizer().tokenize(s), number=100)
9.424515363003593
```

**Comment by earwig** [comment]
This looks like #42, but after thinking on it for a bit I've come up with a better solution to this general problem than what I had thought of previously. It should be much easier to implement. Stay tuned...

**Comment by Riamse** [comment]
S U C K  I T  M I C R O $ O F T
