### ISSUE TITLE
Definition term and description tags should contain their content

### ISSUE THREAD

**Issue by Larivact** [earwig/mwparserfromhell#184]
```
>>> import mwparserfromhell as mw
>>> mw.parse('; test').nodes
[';', ' test']
>>> mw.parse(': test').nodes
[':', ' test']
```
When I am looking for top level Text nodes I don't want dt and and dd contents.

**Comment by lahwaacz** [comment]
This is basically the same problem as #46, although the title specifies only "list tags".

**Comment by earwig** [comment]
Technically definition lists are a type of list (I think?), so yes. Will mark as a duplicate.
