### ISSUE TITLE
Incorrect detection of <ref> tags.

### ISSUE THREAD

**Issue by eggpi** [earwig/mwparserfromhell#187]
Hi, I'm running into a couple of cases where the parser seems to give incorrect results for filtering `<ref>` tags. The specific pages I'm looking at are:

https://en.wikipedia.org/wiki/List_of_German-speaking_Academy_Award_winners_and_nominees
https://en.wikipedia.org/wiki/List_of_French_marquisates

Note how the former has 2 <ref> tags, and the latter only has one. However, using `filter_tags('ref')` as in the following code sample:

~~~python
import json
from urllib import urlencode
from urllib import urlopen
import mwparserfromhell as mwp

API_URL = "https://en.wikipedia.org/w/api.php"

print mwp.__version__  # 0.4

def get_page_by_id(id):
    data = {"action": "query", "prop": "revisions", "rvlimit": 1,
            "rvprop": "content", "format": "json", "pageids": id}
    raw = urlopen(API_URL, urlencode(data).encode()).read()
    res = json.loads(raw)
    return res["query"]["pages"].values()[0]["revisions"][0]["*"]

wdoc = mwp.parse(get_page_by_id('19808098'))  # or 36185579
print len(wdoc.filter_tags('ref'))
~~~

Tells me that the first page has ~3000 tags, and the second has over 18000.

**Comment by earwig** [comment]
This one is a little strange. You want `filter_tags(matches=lambda t: t.tag == 'ref')`.

The filter_* methods don't take positional arguments, so Python helpfully has you calling `filter_tags(recursive="ref")` which just ends up returning a list of every tag in the page, recursively.
