### ISSUE TITLE
Parse stalls out with an example

### ISSUE THREAD

**Issue by rexdouglass** [earwig/mwparserfromhell#190]
I've parsed most of wikipedia successfully using mwparserfromhell.parse (called from R using Reticulate)

I've discovered one article that causes parse to hang forever.

I'm including it here below in case it's an edge case that is interesting. Maybe there's some weird recursion in the templates.

The text block from "[Virginia Constitutional Convention of 1829–1830" ](https://en.wikipedia.org/wiki/Virginia_Constitutional_Convention_of_1829%E2%80%931830)

"[[File:PPBarbour.jpg|right|thumb|150px|<center>[[Philip P. Barbour]]<br>Presiding officer]] The '''Virginia Constitutional Convention of 1829–1830''' was a constitutional convention for the [[U.S. state|state]] of [[Virginia]], held in [[Richmond, Virginia|Richmond]] from October 5, 1829 to January 15, 1830.  == Background and composition == {{History of Virginia}}  Almost immediately, the Constitution of 1776 was recognized as flawed both for its restriction of the suffrage by property requirements, and for its malapportionment favoring the smaller eastern counties. Between 1801 and 1813, petitioners called on the Assembly to initiate a constitutional convention ten times.  The House of Delegates passed a bill twice, but the conservative eastern planter majority in the Virginia Senate killed both measures. Continuing growth in the western parts of the state led to another fifteen years of agitation. Several counties in the Eastern Shore, northern Piedmont and western counties began opening polls for direct expression from the voters for a constitutional convention, eventually there were twenty-eight such counties calling for reform.<ref>[[#shade|Shade 1996]], p. 57-61</ref>  [[File:1830VAConstConv01.jpg|260px|thumb|right|''The Virginia Constitutional Convention, 1830'', by [[George Catlin]]]]  Malapportionment in the Assembly was seen as “an usurpation of the minority over the majority” by the slave owning eastern aristocracy. Partisans argued for apportionment by white population, versus “federal numbers” combining white population with three-fifths slaves, versus the existing system counting whites and slaves equally to favor the slave-holding eastern counties. After several General Assembly sessions with close votes for calling a convention, in 1828 the Assembly allowed for a statewide ballot for “Convention”, “Neutral” or “No Convention”. It passed by 56.8 percent, with most convention support coming from west of the Blue Ridge Mountains northwest to the Ohio River. But the easterners in the State Senate had stacked the deck in their favor, by apportioning the delegates by four per Senate district, producing a group of men which was more wealthy and more conservative than the House of Delegates.<ref>[[#shade|Shade 1996]], p. 62-64</ref>  The last \"gathering of giants\"<ref>[[#gutzman|Gutzman 2007]], p. 163, 165</ref> from the Revolutionary generation included former presidents James Madison and James Monroe, and sitting Chief Justice John Marshall. But three generations were represented among those who would serve in public office including three presidents, seven U.S. Senators, fifteen U.S. Representatives and four governors. The other delegates to the Convention were sitting judges or members of the Virginia General Assembly.<ref>[[#gutzman|Gutzman 2007]], p. 163, 165</ref>  == Meeting and debate == The Convention met from October 5, 1829 – January 15, 1830, and elected former president [[James Monroe]] of Loudoun its presiding officer. On December 8, Monroe withdrew due to failing health, and the Convention elected [[Philip Pendleton Barbour]] as its new presiding officer. Barbour was a former Speaker of the U.S. House of Representatives, a sitting federal district judge, and a future Justice on the Supreme Court. Conservatives among the Old Republicans such as [[John Randolph of Roanoke]] feared any change from the Founders' 1776 Constitution would lead to an ideological anarchy of “wild abstractions” imposed by egalitarian “French Jacobins” through “this maggot of innovation”. In answer, [[John Marshall]] advanced his view with a petition from the freeholders of Richmond which observed that, “Virtue, intelligence, are not among the products of the soil. Attachment to [slave] property, often a sordid sentiment, is not to be confounded with the sacred flame of patriots.” Any white male who had served in the War of 1812 or who would serve in the militia in there future defense of the country deserved the right to vote.<ref>[[#shade|Shade 1996]], pp. 65–66</ref>  {|align=right |<gallery perrow=2> File:John Wesley Jarvis - John Randolph - Google Art Project.jpg|<center>[[John Randolph of Roanoke|John Randolph]]<br>Conservative</center> File:John Marshall by Henry Inman, 1832.jpg|<center>[[John Marshall]]<br>Reformer</center> File:Abel P. Upshur SecNavy.jpg|<center>[[Abel P. Upshur]]<br>Conservative</center> File:Portrait of Thomas Jefferson Randolph.jpg|<center>[[Thomas Jefferson Randolph|Thomas J. Randolph]]<br>for gradual emancipation</center> </gallery> |}  [[Abel P. Upshur]], a judge on the Virginia General Court, spoke for conservatives when he asserted that there “is a majority of interest as well as a majority in number”. Because both persons and property were the “elements of society”, majority rule by the people alone was not an equitable solution. “Those who have the greatest [property] stake in the Government…[must] have the greatest share of power in the administration of it.” Lawyer John R. Cooke, a veteran of the War of 1812 countered that delegates must base the Constitution and legislative representation on the wishes of citizens, “the white population…[looking] to the people” for its authority, not only the wealthy, not to sectional slave-holding interests, and \"not to the supposed rights of the [unequally populated] counties.”<ref>[[#shade|Shade 1996]], pp. 65</ref>  Reformers' efforts to adopt direct popular election of the Governor were defeated in favor of continuing election by the General Assembly.<ref>[[#gutzman|Gutzman 2007]], p. 188</ref> [[Thomas Jefferson Randolph]], Thomas Jefferson’s grandson, proposed gradual emancipation, a suggestion which never made it out of committee onto the Convention floor.<ref>[[#andrews|Andrews 1937]], p. 430</ref> The reformers lost on almost every issue. Nevertheless, even with the exaggerated Virginia Senate representation apportioning the delegates in favor of the status quo, the three most important roll calls were close.  The “white” population basis of apportioning the General Assembly failed by two votes. The extension of the vote to all free white males failed by two votes. When the popular election of governor passed on its first vote, it failed on reconsideration. The divisions which would lead to West Virginia’s split were evident. Regardless of the various ideologies represented or delegate political affiliation, the final vote 55 for the proposed Constitution to 40 against was along an east-west divide. Only one delegate voted yes from west of the Blue Ridge Mountains.<ref>[[#heinemann|Heinemann 2007]], p. 173-174</ref>  ==Outcomes== [[File:View of Capitol, Richmond, Va. April,1865 - NARA - 529087.tif|thumb|200px|right|[[Virginia State Capitol|Capitol]] at Richmond VA, where Convention of 1829-30 met]] Some malapportionment in the General Assembly was eased relative to the majority of voters and white population in the Valley in the House of Delegates, but nothing for the transmontane west. Some suffrage restrictions were modified to include long term leaseholders and male heads of household.<ref>[[#shade|Shade 1996]], p. 64</ref> The Constitution of 1830 was a \"triumph of traditionalism.”<ref>[[#heinemann|Heinemann 2007]], p. 173</ref>  == Notable attendees and chart of delegates == *[[James Madison]] *[[John Marshall]] *[[James Monroe]]<ref>[[#gutzman|Gutzman 2007]], p. 163, 165</ref> *[[John Randolph of Roanoke]]  The delegates to the Virginia Convention of 1829-1830 – elected in May and June, 1829 at the County Courts. (Ninety-six members, four from each Senatorial District<ref>[[#pulliam|Pulliam 1901, p. 67, 70-72]]</ref>  {| class=\"wikitable\" |- ! District ! Name ! County |- | Amelia, Chesterfield, Cumberland, Nottoway, Powhatan and Town of Petersburg | | |- | <div style=\"text-align: right;”>future U.S. Congressman</div> | [[John Winston Jones]] | [[Chesterfield County, Virginia|Cheserfield]] |- | <div style=\"text-align: right;”>future U.S. Senator</div> | [[Benjamin W. Leigh]] | [[Chesterfield County, Virginia|Chesterfield]] |- | <div style=\"text-align: right;”>Virginia Senator</div> | [[Samuel Taylor (Virginian)|Samuel Taylor]] | [[Chesterfield County, Virginia|Chesterfield]] |- | <div style=\"text-align: right;”>Governor</div> | [[William B. Giles]] | [[Amelia County, Virginia|Amelia]] |- | Brunswick, Dinwiddie, Lunenburg, and Mecklenburg | | |- | <div style=\"text-align: right;”>militia Brigadier General</div> | [[William Henry Brodnax]] | [[Dinwiddie County, Virginia|Dinwiddie]] |- | | George C. Groomgoole | [[Brunswick County, Virginia|Brunswick]] |- | <div style=\"text-align: right;”>past U.S. Congressman</div> | [[Mark Alexander (politician)|Mark Alexander]] | [[Mecklenburg County, Virginia|Mecklenburg]] |- | <div style=\"text-align: right;”>future U.S. Congressman</div> | [[William O. Goode]] | [[Mecklenburg County, Virginia|Mechlenburg]] |- | City of Williamsburg, Charles City, Elizabeth City, James City, City of Richmond,<br>Henrico, New Kent, Warwick and York | | |- | <div style=\"text-align: right;”>U.S. Chief Justice</div> | [[John Marshall]] | [[Richmond, Virginia|Richmond City]] |- | <div style=\"text-align: right;”>U.S. Senator, future President</div> | [[John Tyler]] | [[Charles City County, Virginia|Charles City]] |- | <div style=\"text-align: right;”>Justice, Virginia General Court</div> | [[Philip N. Nicholas]] | [[Richmond, Virginia|Richmond City]] |- | <div style=\"text-align: right;”>Va Senator, Justice</div> | [[John B. Clopton (jurist)|John B. Clopton]] | [[New Kent County, Virginia|New Kent]] |- | Shenandoah and Rockingham | | |- | <div style=\"text-align: right;”>Virginia Senator</div> | [[Peachy Harrison]] | [[Rockingham County, Virginia|Rockingham]] |- | | Jacob Williamson | [[Rockingham County, Virginia|Rockingham]] |- | <div style=\"text-align: right;”>former Va Delegate</div> | William Anderson | [[Shenandoah County, Virginia|Shenandoah]] |- | | Samuel Coffman | [[Shenandoah County, Virginia|Shenandoah]] |- | Augusta, Rockbridge, Pendleton | | |- | <div style=\"text-align: right;”>militia Major General, later Va justice</div> | [[Briscoe Baldwin|Briscoe G. Baldwin]] | [[Augusta County, Virginia|Augusta]] |- | <div style=\"text-align: right;”>Virginia Senator</div> | [[Chapman Johnson]] | [[Augusta County, Virginia|Augusta]] |- | <div style=\"text-align: right;”>U.S. Congressman</div> | [[William McCoy (congressman)|William McCoy]] | [[Pendleton County, West Virginia|Pendleton]] |- | <div style=\"text-align: right;”>future U.S. Congressman</div> | [[Samuel M. Moore]] | [[Rockbridge County, Virginia|Rockbridge]] |- | Monroe, Greenbriar, Bath, Botetourt, Alleghany, Pocahontas, Nicholas | | |- | <div style=\"text-align: right;”>future U.S. Congrssman</div> | [[Andrew Beirne]] | [[Monroe County, West Virginia|Monroe]] |- | <div style=\"text-align: right;”>former U.S. Congressman</div> | [[William Smith (Virginia representative)|William Smith]] | [[Greenbrier County, West Virginia|Greenbrier]] |- | <div style=\"text-align: right;”>Virginia Senator</div> | [[Fleming B. Miller]] | [[Botetourt County, Virginia|Botetourt]] |- | <div style=\"text-align: right;”>Virginia Senator</div> | John Baxter | [[Pocahontas County, West Virginia|Pocahontas]] |- | Sussex, Surry, Southampton, Isle of Wight, Prince George, Greensville | | |- | <div style=\"text-align: right;”>future U.S. Representative, Federal Judge</div> | [[John Y. Mason]] | [[Southampton County, Virginia|Southampton]] |- | <div style=\"text-align: right;”>U.S. Congressman</div> | [[James Trezvant]] | [[Southampton County, Virginia|Southampton]] |- | <div style=\"text-align: right;”>Virginia Delegate</div> | Augustine Claiborne | [[Greensville County, Virginia|Greensville]] |- | | John Urquhart | [[Southampton County, Virginia|Southampton]] |- | Charlotte, Halifax, and Prince Edward | | |- | <div style=\"text-align: right;”>past U.S. Senator; U.S. Congressman</div> | [[John Randolph of Roanoke|John Randolph]] | [[Charlotte County, Virginia|Charlotte]] |- | <div style=\"text-align: right;”>Virginia jurist</div> | [[William Leigh (judge)|William Leigh]] | [[Halifax County, Virginia|Halifax]] |- | <div style=\"text-align: right;”>Virginia Senator</div> | Richard Logan | [[Halifax County, Virginia|Halifax]] |- | <div style=\"text-align: right;”>Upper Appomattox Canal Co.</div> | [[Richard N. Venable]] | [[Prince Edward County, Virginia|Prince Edward]] |- | Spotsylvania, Louisa, Orange, and Madison | | |- | <div style=\"text-align: right;”>Former President</div> | [[James Madison]] | [[Orange County, Virginia|Orange]] |- | <div style=\"text-align: right;”>presiding officer, U.S. Justice</div> | [[Philip P. Barbour]] | [[Orange County, Virginia|Orange]] |- | <div style=\"text-align: right;”>Assembly Delegate; died without attending</div> | David Watson | [[Louisa County, Virginia|Louisa]] |- | <div style=\"text-align: right;”>Virginia Justice</div> | [[Robert Stanard]] | [[Spotsylvania County, Virginia|Spotsylvania]] |- | Loudoun and Fairfax | | |- | <div style=\"text-align: right;”>Former President</div> | [[James Monroe]] | [[Loudoun County, Virginia|Loudoun]] |- | <div style=\"text-align: right;”>U.S. Congressman</div> | [[Charles F. Mercer]] | [[Loudoun County, Virginia|Loudoun]] |- | <div style=\"text-align: right;”>Virginia Senator</div> | William H. Fitzhugh | [[Fairfax County, Virginia|Fairfax]] |- | | Richard H. Henderson | [[Loudoun County, Virginia|Loudoun]] |- | Frederick and Jefferson | | |- | | [[John R. Cocke]] | [[Frederick County, Virginia|Frederick]] |- | <div style=\"text-align: right;”>Former U.S. Congressman</div> | [[Alfred H. Powell]] | [[Frederick County, Virginia|Frederick]] |- | <div style=\"text-align: right;”>resigned</div> | Hierome L. Opie | [[Jefferson County, West Virginia|Jefferson]] |- | <div style=\"text-align: right;”>Future U.S. Senator</div> | [[James M. Mason]] | [[Jefferson County, West Virginia|Jefferson]] |- | <div style=\"text-align: right;”>Assembly Delegate</div> | Thomas Griggs, Jr. | [[Jefferson County, West Virginia|Jefferson]] |- | Hampshire, Hardy, Berkeley and Morgan | | |- | <div style=\"text-align: right;”>Assembly Delegate</div> | William Naylor | [[Hampshire County, West Virginia|Hampshire]] |- | <div style=\"text-align: right;”>Virginia Senator</div> | William Donaldson | [[Hampshire County, West Virginia|Hampshire]] |- | <div style=\"text-align: right;”>militia Brigadier General, Virginia Senator</div> | [[Elisha Boyd]] | [[Berkeley County, West Virginia|Berkeley]] |- | <div style=\"text-align: right;”>U.S. Judge</div> | [[Philip Pendleton]] | [[Berkeley County, West Virginia|Berkeley]] |- | Washington, Lee, Scott, Russell and Tazewell | | |- | <div style=\"text-align: right;”>Assembly Delegate</div> | John B. George | [[Tazewell County, Virginia|Tazewell]] |- | <div style=\"text-align: right;”>Assembly Delegate</div> | Andrew McMilian | [[Lee County, Virginia|Lee]] |- | | Edward Campbell | [[Washington County, Virginia|Washington]] |- | <div style=\"text-align: right;”>Assembly Delegate</div> | William Byars | [[Washington County, Virginia|Washington]] |- | King William, King and Queen, Essex, Caroline and Hanover | | |- | <div style=\"text-align: right;”>U.S. Congressman</div> | [[John Roane]] | [[King William County, Virginia|King William]] |- | <div style=\"text-align: right;”>U.S. Congressman</div> | [[William P. Taylor]] | [[Caroline County, Virginia|Caroline]] |- | <div style=\"text-align: right;”>Assembly Delegate</div> | Richard Morris | [[Hanover County, Virginia|Hanover]] |- | <div style=\"text-align: right;”>former U.S. Congressman</div> | [[James M. Garnett]] | [[Essex County, Virginia|Essex]] |- | Wythe, Montgomery, Grayson and Giles | | |- | | Gordon Cloyd | [[Montgomery County, Virginia|Montgomery]] |- | <div style=\"text-align: right;”>Virginia Senator</div> | Henley Chapman | [[Giles County, Virginia|Giles]] |- | | John P. Mathews | [[Wythe County, Virginia|Wythe]] |- | <div style=\"text-align: right;”>Assembly Delegate</div> | William Oglesby | [[Grayson County, Virginia|Grayson]] |- | Kanawha, Mason, Cabell, Randolph, Harrison, Lewis, Wood and Logan | | |- | <div style=\"text-align: right;”>Virginia Senator</div> | Edwin S. Duncan | [[Harrison County, West Virginia|Harrison]] |- | <div style=\"text-align: right;”>Assembly Delegate</div> | [[John Laidley]] | [[Cabell County, West Virginia|Cabell]] |- | <div style=\"text-align: right;”>Assembly Delegate</div> | [[Lewis Summers (Virginian)|Lewis Summers]] | [[Kanawha County, West Virginia|Kanawha]] |- | <div style=\"text-align: right;”>Assembly Delegate</div> | Adam See | [[Randolph County, West Virginia|Randolph]] |- | Ohio, Tyler, Brooke, Monongalia and Preston | | |- | <div style=\"text-align: right;”>U.S. Congressman</div> | [[Philip Doddridge (Virginia)|Philip Doddridge]] | [[Brooke County, West Virginia|Brooke]] |- | <div style=\"text-align: right;”>Virginia Senator</div> | Charles S. Morgan | [[Monongalia County, West Virginia|Monongalia]] |- | <div style=\"text-align: right;”>future Pres., Bethany College</div> | [[Alexander Campbell (clergyman)|Alexander Campbell]] | [[Brooke County, West Virginia|Brooke]] |- | | Eugenius M. Wilson | [[Monongalia County, West Virginia|Monongalia]] |- | Fauquier and Culpeper | | |- | <div style=\"text-align: right;”>U.S. Congressman</div> | [[John S. Barbour]] | [[Culpeper County, Virginia|Culpeper]] |- | <div style=\"text-align: right;”>Virginia Senator</div> | John Scott | [[Fauquier County, Virginia|Fauquier]] |- | <div style=\"text-align: right;”>Assembly Delegate</div> | John Macrae | [[Fauquier County, Virginia|Fauquier]] |- | <div style=\"text-align: right;”>Virginia Justice</div> | [[John W. Green]] | [[Culpeper County, Virginia|Culpeper]] |- | Norfolk, Princess Anne, Nansemond and Borough of Norfolk | | |- | <div style=\"text-align: right;”>U.S. Senator; future Governor</div> | [[Littleton W. Tazewell]] | [[Norfolk, Virginia|Norfolk Borough]] |- | | Joseph Prentis | [[Nansemond County, Virginia|Nansemond]] |- | <div style=\"text-align: right;”>resigned</div> | [[Robert B. Taylor (Virginian)|Robert B. Taylor]] | [[Norfolk, Virginia|Norfolk Borough]] |- | <div style=\"text-align: right;”>Assembly Delegate</div> | [[Hugh Blair Grigsby]]<ref>[[#pulliam|Pulliam 1901, p. 77]]</ref> | [[Norfolk, Virginia|Norfolk Borough]] |- | <div style=\"text-align: right;”>U.S. Congressman</div> | [[George Loyall]] | [[Norfolk, Virginia|Norfolk Borough]] |- | Campell, Buckingham and Bedford | | |- | <div style=\"text-align: right;”>Virginia Senator</div> | William Campbell | [[Bedford County, Virginia|Bedford]] |- | | Samuel Claytor | [[Campbell County, Virginia|Campbell]] |- | <div style=\"text-align: right;”>resigned</div> | Callowhill Mennis | [[Bedford County, Virginia|Bedford]] |- | <div style=\"text-align: right;”>Virginia Senator</div> | James Saunders | [[Campbell County, Virginia|Campbell]] |- | Franklin, Patrick, Henry and Pittsylvania | | |- | <div style=\"text-align: right;”>Virginia Senator</div> | George Townes | [[Pittsylvania County, Virginia|Cheserfield]] |- | <div style=\"text-align: right;”>Virginia Senator</div> | Benjamin W. S. Cabell | [[Pittsylvania County, Virginia|Pittsylvania]] |- | <div style=\"text-align: right;”>Virginia Senator</div> | Joseph Martin | [[Henry County, Virginia|Henry]] |- | <div style=\"text-align: right;”>future U.S. Congressman</div> | [[Archibald Stuart]] | [[Patrick County, Virginia|Patrick]] |- | Albemarle, Amherst, Nelson, Fluvanna and Goochland | | |- | <div style=\"text-align: right;”>former U.S. Senator, Governor</div> | [[James Pleasants]] | [[Goochland County, Virginia|Goochland]] |- | <div style=\"text-align: right;”>U.S. Congressman</div> | [[William F. Gordon]] | [[Albemarle County, Virginia|Albemarle]] |- | <div style=\"text-align: right;”>Virginia jurist</div> | [[Lucas P. Thompson]] | [[Amherst County, Virginia|Amherst]] |- | <div style=\"text-align: right;”>Assembly Delegate</div> | Thomas Massie, Jr. | [[Nelson County, Virginia|Nelson]] |- | King George, Westmoreland, Lancaster, Northumberland, Richmond,<br>Stafford and Prince William | | |- | <div style=\"text-align: right;”>Virginia Senator; died</div> | William A. G. Dade | [[Prince William County, Virginia|Prince William]] |- | <div style=\"text-align: right;”>former Virginia Senator</div> | Ellyson Currie | [[Lancaster County, Virginia|Lancaster]] |- | <div style=\"text-align: right;”>former U.S. Congressman</div> | [[John Taliaferro]] | [[King George County, Virginia|King George]] |- | | Fleming Bates | [[Northumberland County, Virginia|Northumberland]] |- | Mattews, Middlesex, Accomack, Northampton and Gloucester | | |- | <div style=\"text-align: right;”>Assembly Delegate</div> | Thomas R. Joynes | [[Accomack County, Virginia|Accomack]] |- | <div style=\"text-align: right;”>former U.S. Congressman</div> | [[Thomas M. Bayly]] | [[Accomack County, Virginia|Accomack]] |- | <div style=\"text-align: right;”>Assembly Delegate; died</div> | Calvin H. Read | [[Northampton County, Virginia|Northampton]] |- | <div style=\"text-align: right;”>Virginia jurist, future Sec. Navy, Sec. State</div> | [[Abel P. Upshur]] | [[Northampton County, Virginia|Northampton]] |}  ==See also== *[[Virginia Conventions]]  == References == {{reflist}}  ==Bibliography== *{{cite book |first=Matthew Page |last=Andrews|title=Virginia, the Old Dominion |publisher=Doubleday, Doran & Company |year=1937 |url=https://www.amazon.com/Virginia-Dominion-Matthew-Page-Andrews/dp/B0006E942K|asin= B0006E942K |ref=andrews}} *{{cite book |authorlink=Kevin R. C. Gutzman |last=Gutzman |first=Kevin R.C. |title=Virginia’s American Revolution: from Dominion to Republic, 1776-1840 |publisher= Lexington Books |year=2007 |isbn=978-0-7391-2131-3 |url=https://www.amazon.com/Virginias-American-Revolution-Dominion-1776-1840/dp/0739121316 |ref=gutzman}} *{{cite book |last=Heinemann |first=Ronald L. |title=Old Dominion, New Commonwealth: a history of Virginia, 1607-2007 |publisher= University of Virginia Press |year=2008 |isbn=978-0-8139-2769-5 |url=https://www.amazon.com/Old-Dominion-New-Commonwealth-1607-2007/dp/0813927692 |ref=heinemann}} *{{cite book |last=Pulliam |first=David Loyd |title=The Constitutional Conventions of Virginia from the foundation of the Commonwealth to the present time |publisher= John T. West, Richmond |year=1901 |isbn= 978-1-2879-2059-5 |url= https://www.amazon.com/Constitutional-Conventions-Virginia-Foundation-Commonwealth/dp/1287920594/ref=sr_1_1?s=books&ie=UTF8&qid=1481563611&sr=1-1&keywords=Constitutional+Conventions+Virginia+Foundation+Commonwealth+Present+Time |ref=pulliam}} *{{cite book |last=Shade |first=William G. |title=Democratizing the Old Dominion: Virginia and the Second Party System, 1824–1861 |publisher=University of Virginia Press |year=1996 |isbn=978-0-8139-1654-5 |url=https://books.google.com/?id=3G2c8Smin6wC |ref=shade}}  ==External links== *[https://archive.org/details/proceedingsandd01virggoog Proceedings and Debates of the Virginia State Convention of 1829–30]. Samuel Shepherd & Co. for Ritchie & Cook 1830 Richmond online from the archives of the University of Virginia at archive.org  {{DEFAULTSORT:Virginia Constitutional Convention of 1829-1830}} [[Category:Political history of Virginia]] [[Category:1829 in Virginia]] [[Category:1830 in Virginia]] [[Category:Constitutional conventions (political meeting)]] [[Category:1829 conferences]] [[Category:1830 conferences]] [[Category:1829 in American politics]] [[Category:1829 in the United States]] [[Category:1830 in American politics]] [[Category:1830 in the United States]]"

**Comment by earwig** [comment]
Thanks for the report. From a quick test, this doesn't seem an infinite loop, but the parser getting stuck in very deep recursion (as you pointed out). The parser is supposed to have a mitigation for this, so something's definitely going wrong. I'll look more carefully later.

**Comment by kireet** [comment]
I've noticed the parser stalling out parsing the source of https://en.wikipedia.org/wiki/NATO_Joint_Military_Symbology

is this the same issue?

**Comment by earwig** [comment]
@kireet, yes, looks like it. They both have HTML tags within table cells with unclosed attributes that the parser is choking on. (`<div style="foo”>` in the first case—note the invalid right fancy quotation mark, and `<span style="foo>` in your case.)

I'm currently working on this.

**Comment by earwig** [comment]
Fixed in 86c805d.

**Comment by kireet** [comment]
great! Are you going to release it to pypi?

**Comment by earwig** [comment]
Done.
