### ISSUE TITLE
Survey: Drop support for Python 2.6, 3.2, 3.3?

### ISSUE THREAD

**Issue by earwig** [earwig/mwparserfromhell#199]
I would like to consider dropping support for EOL'd versions of Python in the next release.

This would reduce the testing complexity and some code paths could be cleaned up, but it's not a substantial savings, so I'd only like to do it if I can confirm that no one out there is relying on this.

Survey: are you or anyone you know still using Python 2.6, 3.2, or 3.3, and are unable to upgrade (due to package managers, pre-installed environments, etc.)?

**Comment by legoktm** [comment]
Pywikibot dropped support for Python 2.6 and 3.3 in April, so no issues from us :).

The main reason we kept 2.6 support for so long was for a few RHEL 6 users but IIRC they upgraded or moved away so we no longer had any real 2.6 users.

Is it possible to get download stats from PyPI?

**Comment by earwig** [comment]
> Is it possible to get download stats from PyPI?

I don't think so, and even then, not sure how useful that would be. We don't build non-Windows wheels (though that will change in the next release), so we can only gather Windows data, and Appveyor already doesn't support 2.6 and 3.2, so we can't even get data for those version...

Yeah, I'm probably going through with this unless someone has an objection.

**Comment by hugovk** [comment]
> Is it possible to get download stats from PyPI?

Yes, it is, for example using https://github.com/ofek/pypinfo.

Here's the pip installs for mwparserfromhell from PyPI for **January** 2018:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  42.12% |          1,488 |
| 3.6            |  16.22% |            573 |
| 3.5            |  12.06% |            426 |
| 3.4            |  10.16% |            359 |
| 2.6            |   9.96% |            352 |
| 3.3            |   9.43% |            333 |
| 3.7            |   0.06% |              2 |
| Total          |         |          3,533 |

Source: `pypinfo --start-date 2018-01-01 --end-date 2018-01-31 --percent -md mwparserfromhell pyversion`

And for **August** 2018:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  85.16% |          7,632 |
| 3.6            |   8.30% |            744 |
| 3.5            |   3.44% |            308 |
| 3.4            |   2.21% |            198 |
| 3.7            |   0.89% |             80 |
| Total          |         |          8,962 |

Source: `pypinfo --start-date 2018-08-01 --end-date 2018-08-31 --percent -md mwparserfromhell pyversion`

EOL versions' share has gone from 20% to 0!

**Comment by hugovk** [comment]
Please see PR https://github.com/earwig/mwparserfromhell/pull/204.
