### ISSUE TITLE
AttributeError: module 'mwparserfromhell' has no attribute 'parse'

### ISSUE THREAD

**Issue by xreader** [earwig/mwparserfromhell#210]
Using example from readme i get this error message

```
Traceback (most recent call last):
  File "wikiparser.py", line 16, in <module>
    main("M1_Abrams")
  File "wikiparser.py", line 13, in main
    return mwparserfromhell.parse(text)
AttributeError: module 'mwparserfromhell' has no attribute 'parse'
```

here is code snipet

```
import json
from urllib.parse import urlencode
from urllib.request import urlopen
import mwparserfromhell
API_URL = "https://en.wikipedia.org/w/api.php"

def main(title):
    data = {"action": "query", "prop": "revisions", "rvlimit": 1,
            "rvprop": "content", "format": "json", "titles": title}
    raw = urlopen(API_URL, urlencode(data).encode()).read()
    res = json.loads(raw)
    text = list(res["query"]["pages"].values())[0]["revisions"][0]["*"]
    return mwparserfromhell.parse(text)

if __name__ == '__main__':
    main("M1_Abrams")
```

**Comment by earwig** [comment]
You haven't installed the parser correctly. Is it possible you downloaded the git repo to your current directory? It seems Python might be trying and failing to import it from there directly.

You'll either need to install it with pip (`pip install mwparserfromhell`, possibly with `--user`), or run `python setup.py install` inside the project (again, possibly with `--user`) to install directly from source.

**Comment by xreader** [comment]
Thanks

the problem was that the library was installed  with```python setup.py install``` but run with python3 command
