### ISSUE TITLE
template.name.matches('...') should treat underscores like blanks

### ISSUE THREAD

**Issue by t-karcher** [earwig/mwparserfromhell#216]
I just noticed that 
`wikicode.filter_templates(matches = lambda n: n.name.matches ('Infobox_Country'))`
matches
`{{Infobox_Country}}`
but not
`{{Infobox Country}}`
although both are referring to the same template. It'd be helpful if the matching algorithm would be adapted to match both variants.

**Comment by earwig** [comment]
This seems reasonable to me.
