### ISSUE TITLE
determine if page is for a person or not.

### ISSUE THREAD

**Issue by rijobro** [earwig/mwparserfromhell#242]
I'd like to be able to return true for Barack Obama's page, and false for Youtube's page. How would I go about doing that? Presumably, different templates are used for people compared to others. 

My current tactic searches the infobox for the presence of a date of birth, but this seems ugly.

**Comment by lahwaacz** [comment]
This is not the task of a wikitext parser which has no idea about the semantic usage of site-specific elements like templates or categories.

**Comment by rijobro** [comment]
ok, thanks

**Comment by earwig** [comment]
Wikidata is probably the way to go for this. (Indeed, not the job of the parser.) There is a programmatic API. People should have a property “instance of” “human” I think.
