### ISSUE TITLE
Pretty printer?

### ISSUE THREAD

**Issue by ctrlcctrlv** [earwig/mwparserfromhell#245]
Is there a pretty printer? If not, should there be one in the default distribution, or is that a job for a third party?

**Comment by clokep** [comment]
There's the [`Wikicode.get_tree()`](https://mwparserfromhell.readthedocs.io/en/latest/api/mwparserfromhell.html#mwparserfromhell.wikicode.Wikicode.get_tree) method which might do what you want.

**Comment by ctrlcctrlv** [comment]
Indeed, thanks :-)

For Google, **mwparserfromhell is a Mediawiki pretty printer / beautifier.** 😜
