### ISSUE TITLE
Detect all table from a wiki dump

### ISSUE THREAD

**Issue by hasantuberlin** [earwig/mwparserfromhell#250]
Hello,
Are there any possibilities to detect table from a wiki dump? I actually did not find documentation on this.

Thank you in advance.

**Comment by lahwaacz** [comment]
Which wiki dump? mwparserfromhell is a parser of MediaWiki markup, not of XML dump files.

**Comment by hasantuberlin** [comment]
Thank you.
In case of MediaWiki markup. How can I do it?

**Comment by lahwaacz** [comment]
See https://github.com/earwig/mwparserfromhell/issues/93.
