### ISSUE TITLE
Is there a way to get MediaWiki lists?

### ISSUE THREAD

**Issue by Mark-L6n** [earwig/mwparserfromhell#258]
Is there a way to get [MediaWiki lists](https://meta.wikimedia.org/wiki/Help:List), that would function something like a hypothetical `get_lists()` or `filter_lists()`?
I looked through [smart_list](https://github.com/earwig/mwparserfromhell/tree/develop/mwparserfromhell/smart_list) and [wikicode.py](https://github.com/earwig/mwparserfromhell/blob/develop/mwparserfromhell/wikicode.py) but didn't figure out how to do this.

**Comment by earwig** [comment]
Hi, unfortunately this is not implemented yet. See #46.
