### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by matkoniecz** [earwig/mwparserfromhell#264]
I just wanted to say "thank you" to all people who made this library, it was [very useful](https://github.com/matkoniecz/osm_wiki_tag_api/blob/master/extract_infobox_data.py) during making systematic improvements to infoboxes on https://wiki.openstreetmap.org/ (detecting missing parameters and producing reports more useful than what categories on wiki could produce).

Hopefully it is OK to make such nonissue, to avoid disturbance I will close it immediately.

**Comment by earwig** [comment]
You're welcome! No problem.
