### ISSUE TITLE
Text node inside Template params shall strip leading and trailing whitespaces

### ISSUE THREAD

**Issue by SrihariThalla** [earwig/mwparserfromhell#266]
~~Possibly related to #55 #265~~

```
{{Cite web | url= https://www.example.com | title=Example }}
```

Parsing and filtering the template and extracting the `url` from the template returns whitespace at both ends.

```python
import mwparserfromhell
from urllib.parse import urlparse

text = '{{Cite web | url= https://www.example.com | title=Example }}'
wikicode = mwparserfromhell.parse(text)

templates = wikicode.filter_templates()
print(templates[0].get('url').value)

o = urlparse(str(templates[0].get('url').value))
print(o)
```

The URL is not parsed. It returns

```
ParseResult(scheme='', netloc='', path=' https://www.example.com ', params='', query='', fragment='')
```

when it should return,

```
ParseResult(scheme='https', netloc='www.example.com', path='', params='', query='', fragment='')
```

**Comment by JJMC89** [comment]
Strip the value instead of casting it to a string.
```python
>>> urlparse(templates[0].get('url').value.strip())
ParseResult(scheme='https', netloc='www.example.com', path='', params='', query='', fragment='')
```

**Comment by lahwaacz** [comment]
This is about templates, not headings, so those issues are not relevant. mwparserfromhell keeps the whitespace, because serializing the parsed object should give the original wikitext exactly, even whitespace changes should not be there. Calling `.strip()` when you need is just a minor user inconvenience.

**Comment by SrihariThalla** [comment]
Thanks for your answers!
