### ISSUE TITLE
add `after` parameter to Template.add() method

### ISSUE THREAD

**Issue by RheingoldRiver** [earwig/mwparserfromhell#281]
This would be a nice QOL update that doesn't really add missing functionality per se, but I often try to convince people how easy it is to edit wikis with Python scripts, and one sticking point is that it's just a *bit* tricky to add one parameter after another, when someone is brand-new to coding. And usually adding a new parameter after an existing one is the desired use case for Template.add (e.g. `template.add('image_unlined', 'Yes', after='image')` etc).

**Comment by earwig** [comment]
Fixed in #315.
