### ISSUE TITLE
template with a leading space before its name on the wiki isn't matched

### ISSUE THREAD

**Issue by RheingoldRiver** [earwig/mwparserfromhell#316]
With the following code:

```python
        for template in wikitext.filter_templates(recursive=self.recursive):
            if template.name.matches(self.template_name):
                # do something
```

If the wiki code is `{{ TemplateName` (i.e. there is a leading space between the braces & the text on the wiki) then `TemplateName` will not match it for this template. Right now I'm thinking the best workaround without side effects is to clone the template, replace the name with its `str(name).strip()` but I think `matches` shouldn't fail here.

**Comment by lahwaacz** [comment]
Works fine for me:
```python
import mwparserfromhell
wikitext = mwparserfromhell.parse("{{ foo | bar }}")
for template in wikitext.filter_templates():
    if template.name.matches("foo"):
        print("found foo")
```

**Comment by RheingoldRiver** [comment]
hmmm I'm a bit confused what's going on now because it was definitely not saving until I did a find-replace of all of the `{{ i` to `{{i` but I can't repro this now, so maybe there was some other problem. I'll close this, sorry for the trouble!
