### ISSUE TITLE
Automatically build Windows Wheels

### ISSUE THREAD

**Issue by valhallasw** [earwig/mwparserfromhell#95]
We can probably auto-build wheels on release using http://www.appveyor.com/ ; I'll fiddle around with it sometime soon(tm).

**Comment by earwig** [comment]
Excellent – this is exactly what we needed.

**Comment by valhallasw** [comment]
https://code.google.com/p/tulip/source/browse/release.py can help to further automate the build process (via http://thread.gmane.org/gmane.comp.python.devel/150912/focus=150957 )

**Comment by valhallasw** [comment]
This was surprisingly easy, thank to https://packaging.python.org/en/latest/appveyor.html . It basically works out-of-the-box... except for the part where tests fail. But at least building and packaging worked for 2.7: https://ci.appveyor.com/project/valhallasw/mwparserfromhell/build/1.0.14/job/u42le32cf1yers7t/artifacts

**Comment by earwig** [comment]
It looks like some of the tests are giving MemoryErrors; never seen that before. Supposedly the build VMs have 1.75 GB free, so I'm not sure why that would happen...

**Comment by valhallasw** [comment]
I'm a step further with the 3.x builds; they don't crash on reading the file with the wrong charset, but now they fail on non-BMP characters. I don't get why, though, as 3.3+ is supposed to have variable-width strings, and reading in the characters from a file works without issues.

As for the MemoryError, it seems that the SmartList is actually growing until the memory is full, because just afterwards, there's a
```
  File "C:\projects\mwparserfromhell\mwparserfromhell\smart_list.py", line 410, in pop
    length = len(self)
OverflowError: long int too large to convert to int
```

which suggests that the list has more than sys.maxint = 2^63 entries. No wonder this causes a MemoryError ;-)

**Comment by earwig** [comment]
Current status: in the `feature/win_builds` branch, for each version of Python supported by mwparserfromhell, we have:

- :white_check_mark: Python 2.7 x86: ~~compiler errors~~ works in a8c0ff3f290cf82da8e22cd0007d78adfed3c4b1
- :x: Python 2.7 x86_64: ~~compiler errors~~ SmartList tests fail, as noted above
- :x: Python 3.3 x86: waiting on #78
- :x: Python 3.3 x86_64: waiting on #78
- :x: Python 3.4 x86: waiting on #78
- :x: Python 3.4 x86_64: waiting on #78
- :x: Python 2.6, 3.2, 3.5: no support in Appveyor... I'm okay with this; 2.6 and 3.2 are old and 3.5 has not been released yet
