### ISSUE TITLE
Parser badly handles triple quotes

### ISSUE THREAD

**Issue by WydD** [earwig/mwparserfromhell#98]
Reproduce:
* use the source from http://bulbapedia.bulbagarden.net/wiki/Audino_%28Pok%C3%A9mon%29
* During the `{{learnlist}}` block everything crumbles
* Templates and links are not extracted the way they should be.

It seems that the triple quotes are badly handled because if I do a straight replace from triple quotes to none, everything works fine. The learnlist block has tons of triple quote as template parameters.

For my usage I used the "replace" solution but that should be fixed.

Cheers

**Comment by earwig** [comment]
Thanks for the report. This is the same as #40, specifically the first issue there. I'm not sure if it's something I'll ever be able to solve within the current parsing framework. At any rate, you can pass `skip_style_tags=True` to `mwparserfromhell.parse()` to get around it. This causes the parser to treat triple (and double) quotes as normal text.
