### ISSUE TITLE
HTML comments prevent proper parsing of templates

### ISSUE THREAD

**Issue by qwrrty** [earwig/mwparserfromhell#99]
If a template includes an HTML comment on a line by itself, between the template name and the first parameter, the parser will silently fail to parse the template.

Example:

These are parsed properly:

    >>> mwparserfromhell.parse('{{foo\n|bar}}').filter_templates()
    [u'{{foo\n|bar}}']
    >>> mwparserfromhell.parse('{{foo|bar}}').filter_templates()
    [u'{{foo|bar}}']
    >>> mwparserfromhell.parse('{{foo|baz\n\n|bar}}').filter_templates()
    [u'{{foo|baz\n\n|bar}}']

But:

    >>> mwparserfromhell.parse('{{foo\n\n|bar}}').filter_templates()
    []

This issue comes up in live text when very large templates use HTML as notes to the user, e.g. https://en.wikipedia.org/wiki/Arroyo_Grande,_California:

    {{Infobox settlement
    
    |official_name            = Arroyo Grande, California
    |other_name               = 
    ....

**Comment by earwig** [comment]
Hi, and thanks for the report. This has already been fixed as #59, so you'll need to update to the parser's `develop` branch before I get around to releasing 0.4. Unfortunately I can make no guarantees as to when that will be.
